# Generated by Django 6.1 on 2026-08-19 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_recentviewedtool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Veylora AI', max_length=100)),
                ('theme_preset', models.CharField(choices=[('midnight', 'Midnight Purple'), ('ocean', 'Ocean Blue'), ('emerald', 'Emerald Green'), ('sunset', 'Sunset Orange'), ('rose', 'Rose Pink'), ('light', 'Clean Light'), ('custom', 'Custom Theme')], default='midnight', max_length=30)),
                ('primary_color', models.CharField(default='#7568ff', max_length=20)),
                ('secondary_color', models.CharField(default='#00d4ff', max_length=20)),
                ('accent_color', models.CharField(default='#d946ef', max_length=20)),
                ('background_color', models.CharField(default='#0b0f19', max_length=20)),
                ('card_color', models.CharField(default='#121827', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('muted_text_color', models.CharField(default='#9da6b8', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Theme',
                'verbose_name_plural': 'Site Theme',
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('request_method', models.CharField(default='GET', max_length=10)),
                ('response_status', models.PositiveIntegerField(default=200)),
                ('referrer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=40)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('operating_system', models.CharField(blank=True, max_length=60)),
                ('is_authenticated_visit', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at', 'path'], name='visit_time_path_idx'), models.Index(fields=['session_key', 'visited_at'], name='visit_session_idx')],
            },
        ),
    ]
